remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "RefinedFields: Radiance Fields Refinement for Unconstrained Scenes"
description: "Anonymous Authors"

show_downloads: true
